// Generated by https://quicktype.io

export interface Product {
  id: number;
  nombre: string;
  descripcion: string;
  cantidadDisponible: number;
  cantidadInicial: number;
  caracteristicas: string;
  imagenes: string;
  precio: number;
  createdAt: string;
  updatedAt: string;
  opiniones: Opinione[];
  categorias: Categoria[];
}

export interface Categoria {
  categoria: string;
  createdAt: string;
  updatedAt: string;
  Categoria: CategoriaClass;
}

export interface CategoriaClass {
  createdAt: string;
  updatedAt: string;
  ProductoId: number;
  CategoriaProductoCategoria: string;
}

export interface Opinione {
  id: number;
  valoracion: string;
  opinion: string;
  createdAt: string;
  updatedAt: string;
  ClienteId: number;
  ProductoId: number;
}
