// Generated by https://quicktype.io

export interface Product {
  id: number;
  nombre: string;
  descripcion: null | string;
  cantidadDisponible: number;
  cantidadInicial: number;
  caracteristicas: string;
  imagenes: string;
  precio: number;
  createdAt: string;
  updatedAt: string;
  Opinions: Opinion[];
  Categorias: CategoriaElement[];
}

export interface CategoriaElement {
  categoria: string;
  createdAt: string;
  updatedAt: string;
  Categoria: CategoriaCategoria;
}

export interface CategoriaCategoria {
  createdAt: string;
  updatedAt: string;
  ProductoId: number;
  CategoriaProductoCategoria: string;
}

export interface Opinion {
  id: number;
  valoracion: number;
  opinion: string;
  createdAt: string;
  updatedAt: string;
  ClienteId: number;
  ProductoId: number;
  Cliente: Cliente;
}

export interface Cliente {
  id: number;
  username: string;
  password: string;
  email: string;
  imageURL: string;
  createdAt: string;
  updatedAt: string;
}
