// Generated by https://quicktype.io

export interface Product {
    id:                 number;
    nombre:             string;
    descripcion:        string;
    cantidadDisponible: number;
    cantidadInicial:    number;
    caracteristicas:    string;
    imagenes:           string;
    precio:             number;
    createdAt:          string;
    updatedAt:          string;
    opiniones:          Opinion[];
    categorias:         Categoria[];
}

export interface Categoria {
    categoria: string;
    createdAt: string;
    updatedAt: string;
    Categoria: CategoriaClass;
}

export interface CategoriaClass {
    createdAt:                  string;
    updatedAt:                  string;
    ProductoId:                 number;
    CategoriaProductoCategoria: string;
}

export interface Opinion {
    id:         number;
    nombre?:     string;
    valoracion: number;
    opinion:    string;
    createdAt:  string;
    updatedAt:  string;
    ClienteId:  number;
    cliente:    Cliente;
    ProductoId: number;
}

export interface Cliente {
    id:         number;
    username:   string;
    password:   string;
    email:      string;
    imageURL:   string;
    createdAt:  string;
    updatedAt:  string;
}
